### PR TITLE
Added a couple of std::map idioms

### PR DESCRIPTION
**Pull request by ilpropheta**
- Check if a key exists in a std::map
- (safe) get of a value corresponding to a key in a std::map

### CODE REVIEW

**Comment by sftrabbit** [comment]
Thanks for the contribution. The map-key-exists sample is useful. I'm not sure about the map-get-value-by-key sample because I don't see why we wouldn't suggest using `operator[]` or `at` if we need bounds-checking. What are your thoughts here?

**Comment by ilpropheta** [comment]
Thanks Joseph! On at/operator[] you're right, but if you want the max efficiency possible then exceptions can hurt a bit. I can modify my example and mention them too (see here https://github.com/italiancpp/CppSamples-Samples/commit/d592fedafff19dd9ad87935b70b9c76ab236e2bd). What do you think?

**Comment by sftrabbit** [comment]
Hey - sorry I haven't gotten back to you yet on this. I'm pretty busy at the moment, but will try to catch up on the C++ Samples stuff soon.

**Comment by ilpropheta** [comment]
No worries Joseph, we can discuss when you have time. I have also other samples to propose!

**Comment by sftrabbit** [comment]
Merged, reviewed, and edited the "key existence" and "tuple unpacking" samples. Great contributions, thanks. Most changes were just simple rewordings, formatting, or matching the style of the site.

**Pull request merged**
