### PR TITLE
Add weak reference example by modifying the observer pattern example

### PR DESCRIPTION
**Pull request by migrantcoder**

### CODE REVIEW

**Comment by sftrabbit** [comment]
Thanks for the contribution. A weak reference example is a great idea. This currently feels like a there's too much observer pattern still there though, which isn't really relevant to the feature. It could really just show a class holding a `weak_ptr` to some shared object that is passed to it from a function. Would you be up for cutting it down like this?

**Comment by migrantcoder** [comment]
Agreed. Will update accordingly.

**Comment by migrantcoder** [comment]
I've cut down the weak reference example by removing the irrelevant observer pattern aspects and emphasized its use to avoid circular references. Let me know if this is what you had in mind.

**Comment by sftrabbit** [comment]
It's looking good! - will review/edit as soon as I can.

**Comment by sftrabbit** [comment]
Great sample. I did an edit commit (see fefc77c). I think I have made the code a little clearer and did a fair bit of rewording in the description (adding proper mark-up and line references). If I've broken anything, let me know, but I think it's turned out great.

**Comment by migrantcoder** [comment]
Looks good. Thank you.

**Pull request merged**
