### PR TITLE
Add perfect-forwarding sample

### PR DESCRIPTION
**Pull request by yacoder**
Re: issue #12 

Hope this helps :)

### CODE REVIEW

**Comment by sftrabbit** [comment]
Looks great! Will review/merge later today.

**Comment by sftrabbit** [comment]
Reviewed, edited, and merged. Just did a bit of simplifying the sample (I try have as little extra detail as possible, even if it makes the sample a bit more unrealistic) and some rewording/clarification in the description. Thanks.

**Comment by sftrabbit** [comment]
By the way, if you want your contribution to link through to your GitHub profile, you need to add your commit email address to your GitHub account settings.

**Comment by yacoder** [comment]
Thanks, Joseph. Do you mean I need to make my email address public in my profile? Or what is "commit email address"?..

**Comment by sftrabbit** [comment]
The way I have the contributors list working is by searching for the commit email address (the one you get when you run `git config user.email`) with the GitHub API and picking the top result. Honestly, I'm not sure if it works with private emails. If not, I might have to rethink this approach!

**Comment by yacoder** [comment]
Yeah, seems like it couldn't link back to my account. I've made my email public just now, so lets see if that helps. But that's somewhat less than ideal, maybe worth opening a separate issue :)

**Pull request merged**
