### PR TITLE
Added snippet to demonstrate count algorithm

### PR DESCRIPTION
**Pull request by jatindhankhar**
Added snippet to demonstrate [count algorithm](http://en.cppreference.com/w/cpp/algorithm/count). Decided to add only count as count_if can be moved to it's own page/file.

### CODE REVIEW

**Comment by sftrabbit** [comment]
Thanks and apologies for the very slow response. I'll be catching up on updating the site this coming weekend, so I'll take a look then.

**Comment by jatindhankhar** [comment]
That's ok. No problem :+1:

**Comment by sftrabbit** [comment]
This has been added to the site with just a bit of tidying up/simplifying. Thanks for your contribution!

**Comment by jatindhankhar** [comment]
Thanks :)
Any plans of adding socket programming in modern cpp style ? As of now, most of the socket programming tutorials are done in c style even for cpp

**Pull request merged**
